### ISSUE TITLE
[help wanted]: conf.yaml problem

### ISSUE THREAD

**Issue by finalha** [veops/messenger#14]
### Contact Details

164970707@qq.com

### What is your question?

i have a question!
auths:
  - type: ip
     pattern: 192.168.\*.\*
  
 If I have more IPs in different domains, for example: 10.10.\*.\* and 175.0.\*.\* and so on. How to write the conf/conf.yaml

### Version

newest

**Comment by ttktatakai** [comment]
@finalha This is not supported yet. But it's a common requirement. Will try to implement it asap.

**Comment by ttktatakai** [comment]
@finalha Is is supported now. Multi ips should be split by , #16
