### ISSUE TITLE
About the atUserIds parameter of dingdingBot 

### ISSUE THREAD

**Issue by duliang123** [veops/messenger#3]
Dingding Normal group: The atUserIds parameter is not supported (only for Internal group of enterprises).
So I had to modify the atUserIds parameter to: atMobiles.
Then @someone works!

`
			at["isAtAll"] = lo.Contains(msg.Ats, "@all")
			at["atMobiles"] = lo.Without(msg.Ats, "@all")
`

**Comment by ttktatakai** [comment]
Is seems that dingding custom bot has been not supported in external group.


![image](https://github.com/veops/messenger/assets/150361932/4ccc1007-bc06-42f3-9aad-65971b72dfcf)

**Comment by duliang123** [comment]
> ternal g

This: 
https://open.dingtalk.com/document/orgapp/webhook-bot-offline-notice

**Comment by ttktatakai** [comment]
> > ternal g
> 
> This: https://open.dingtalk.com/document/orgapp/webhook-bot-offline-notice

I have checked the link you provided and since custom bot is not supported in external any more(your normal group means external group, right?), I donot have environment to test it.
Sorry for this inconvenience.
But it may be a good idea to add some parameters to distinguish at by user id or at by mobile.

**Comment by duliang123** [comment]
> > > ternal g
> > 
> > 
> > This: https://open.dingtalk.com/document/orgapp/webhook-bot-offline-notice
> 
> I have checked the link you provided and since custom bot is not supported in external any more(your normal group means external group, right?), I donot have environment to test it. Sorry for this inconvenience. But it may be a good idea to add some parameters to distinguish at by user id or at by mobile.

Yes, My Normal Group means external group.
`Add some parameters to distinguish at by user id or at by mobile`, That's good!

**Comment by ttktatakai** [comment]
> > > > ternal g
> > > 
> > > 
> > > This: https://open.dingtalk.com/document/orgapp/webhook-bot-offline-notice
> > 
> > 
> > I have checked the link you provided and since custom bot is not supported in external any more(your normal group means external group, right?), I donot have environment to test it. Sorry for this inconvenience. But it may be a good idea to add some parameters to distinguish at by user id or at by mobile.
> 
> Yes, My Normal Group means external group. `Add some parameters to distinguish at by user id or at by mobile`, That's good!

May check this one [https://github.comhttps://github.com/veops/messenger/pull/5](https://github.comhttps://github.com/veops/messenger/pull/5)

**Comment by duliang123** [comment]
> > > > > ternal g
> > > > 
> > > > 
> > > > This: https://open.dingtalk.com/document/orgapp/webhook-bot-offline-notice
> > > 
> > > 
> > > I have checked the link you provided and since custom bot is not supported in external any more(your normal group means external group, right?), I donot have environment to test it. Sorry for this inconvenience. But it may be a good idea to add some parameters to distinguish at by user id or at by mobile.
> > 
> > 
> > Yes, My Normal Group means external group. `Add some parameters to distinguish at by user id or at by mobile`, That's good!
> 
> May check this one #5

Done!
It works, thanks.

**Comment by ttktatakai** [comment]
@duliang123 Based on my testing, `at by moblie` is not fully supported in all of wechat, feishu and dingding as `at by user id`. Try to use `at by user id` whenever you can :)
